### ISSUE TITLE
Remove dummy text and floating action button

### ISSUE THREAD

**Issue by mayank-kgp** [mayank-kgp/VoiceCalculator#2]
**Summary:** 

Remove dummy text and floating action button.

**Steps to reproduce:** 

Open the main activity of app.

**Expected behavior:** 

No useless buttons, text.

**Observed behavior:** 

Useless text and floating action button.

**Device and Android version:** 

Yureka with android 5.1.1

**Screenshots:** 

![vc1](https://cloud.githubusercontent.com/assets/11210887/20834540/fbafee18-b8bb-11e6-870d-1f97a18bc3ac.png)

**Comment by RanchoDbest** [comment]
I have solved this issue and I sent pull request please merge my pull request.
