### ISSUE TITLE
Voice Button need to be Shifted

### ISSUE THREAD

**Issue by RavneetDTU** [mayank-kgp/VoiceCalculator#26]
**Summary:** 

If Voice button can be shifted with Equal Button than More Space will be available, and can be Used to Increase size of Text (Currently Text Size is Small )

**Device and Android version:** 
Device : MOTO G5+
Screen Size : 5.2'
Android Version : 7.0 (API Level 24)

**Screenshots:** 
![img-20171201-wa0000](https://user-images.githubusercontent.com/25255068/33453350-4dba67fe-d63b-11e7-83ff-bff05ca07616.jpg)

**Comment by Pritom14** [comment]
This should be discussed under changing the UI issue, because the whole UI
needs to be updated. Once the final UI is decided we can update/tweak small
parts/views

**Comment by Pritom14** [comment]
For now this issue should be kept for consideration.

**Comment by mayank-kgp** [comment]
@RavneetDTU This issue can be incorporated in #19
